CREATE OR REPLACE PROCEDURE update_tax (TAX_RATE IN NUMBER)
AS
    L_ELEGIBLE BOOLEAN;
    TYPE ORDERID_TYPE IS TABLE OF SALES.ORDER_ID%TYPE INDEX BY PLS_INTEGER; -- ASSOCIATIVE ARRAY
    L_ORDER_IDS ORDERID_TYPE;
BEGIN

SELECT DISTINCT ORDER_ID BULK COLLECT INTO L_ORDER_IDS
FROM SALES;

FORALL INDEX IN 1 .. L_ORDER_IDS.COUNT
    UPDATE SALES S
    SET S.TAX_AMOUNT = S.TOTAL_AMOUNT * TAX_RATE
    WHERE S.ORDER_ID = L_ORDER_IDS(INDEX)

END;